-- Script d'initialisation de données Kijoukoi (PostgreSQL)

-- 1. Nettoyage (optionnel si les tables viennent d'être créées)
DELETE FROM player_tags;
DELETE FROM player;
DELETE FROM blade;
DELETE FROM rubber;
DELETE FROM player_tag;
DELETE FROM brand;

-- 2. Insertion des Marques
INSERT INTO brand (id, name) VALUES (1, 'Butterfly');
INSERT INTO brand (id, name) VALUES (2, 'Tibhar');
INSERT INTO brand (id, name) VALUES (3, 'Donic');
INSERT INTO brand (id, name) VALUES (4, 'Stiga');
INSERT INTO brand (id, name) VALUES (5, 'Joola');
INSERT INTO brand (id, name) VALUES (6, 'Xiom');
INSERT INTO brand (id, name) VALUES (7, 'Yasaka');
INSERT INTO brand (id, name) VALUES (8, 'Cornilleau');

-- Image générique Base64 (Pixel transparent 1x1) pour l'exemple
-- Dans une vraie appli, ce serait une vraie image base64.
-- 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='

-- 3. Insertion de 20 Bois
INSERT INTO blade (id, name, brand_id, weight, image) VALUES
(1, 'Viscaria ALC', 1, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(2, 'Timo Boll ALC', 1, 86, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(3, 'Zhang Jike Super ZLC', 1, 90, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(4, 'Innerforce Layer ALC', 1, 88, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(5, 'Ovtcharov Innerforce ALC', 1, 86, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(6, 'Samsonov Force Pro Black Edition', 2, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(7, 'Stratus Power Wood', 2, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(8, 'Lebesson', 2, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(9, 'Waldner Senso Carbon', 3, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(10, 'Ovtcharov True Carbon', 3, 88, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(11, 'Appelgren Allplay', 3, 80, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(12, 'Clipper Wood', 4, 90, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(13, 'Infinity VPS V', 4, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(14, 'Carbonado 145', 4, 92, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(15, 'Energon Super PBO-c', 5, 87, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(16, 'Vyzaryz Trinity', 5, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(17, 'Stradivarius', 6, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(18, 'Ice Cream AZXi', 6, 86, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(19, 'Ma Lin Extra Offensive', 7, 85, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(20, 'Gatien Absolut', 8, 86, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=');

-- 4. Insertion de 30 Revêtements
INSERT INTO rubber (id, name, brand_id, image) VALUES
(1, 'Tenergy 05', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(2, 'Tenergy 80', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(3, 'Tenergy 64', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(4, 'Tenergy 19', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(5, 'Dignics 09C', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(6, 'Dignics 05', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(7, 'Rozena', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(8, 'Evolution MX-P', 2, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(9, 'Evolution EL-P', 2, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(10, 'Evolution FX-P', 2, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(11, 'Quantum X Pro', 2, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(12, 'Bluefire M1', 3, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(13, 'Bluefire M2', 3, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(14, 'Bluestorm Z1', 3, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(15, 'Acuda S1', 3, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(16, 'DNA Pro H', 4, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(17, 'DNA Pro M', 4, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(18, 'Mantra H', 4, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(19, 'Dynaryz AGR', 5, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(20, 'Rhyzm', 5, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(21, 'Vega Pro', 6, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(22, 'Vega Europe', 6, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(23, 'Omega VII Pro', 6, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(24, 'Rakza 7', 7, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(25, 'Rakza Z', 7, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(26, 'Mark V', 7, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(27, 'Target Pro GT-H47', 8, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(28, 'Pilot Advance', 8, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(29, 'Tenergy 05 FX', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII='),
(30, 'Dignics 80', 1, 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=');

-- 5. Insertion de PlayerTags
INSERT INTO player_tag (id, name) VALUES (1, 'Attaquant'), (2, 'Défenseur'), (3, 'Allround'), (4, 'Topspinneur'), (5, 'Bloqueur');

-- 6. Insertion de 10 Players
INSERT INTO player (id, login, password, age, nationality, ranking, registration_date, blade_id, forehand_rubber_id, backhand_rubber_id) VALUES
(1, 'sebastien.pong', 'pass123', 25, 'FR', 1800, CURRENT_TIMESTAMP, 1, 1, 3),
(2, 'ma.long', 'dragon', 34, 'CN', 3500, CURRENT_TIMESTAMP, 1, 5, 1),
(3, 'timo.boll', 'legend', 42, 'DE', 3100, CURRENT_TIMESTAMP, 2, 1, 1),
(4, 'jean.michel', 'azerty', 50, 'BE', 1200, CURRENT_TIMESTAMP, 11, 22, 26),
(5, 'fzd_fan', 'fzd2024', 21, 'FR', 2000, CURRENT_TIMESTAMP, 1, 5, 5),
(6, 'dima.ovtcharov', 'serveur', 35, 'DE', 3000, CURRENT_TIMESTAMP, 10, 12, 13),
(7, 'hugo.calderano', 'brazil', 28, 'BR', 3200, CURRENT_TIMESTAMP, 15, 19, 19),
(8, 'lin.yunju', 'backhand', 22, 'TW', 3150, CURRENT_TIMESTAMP, 3, 5, 6),
(9, 'alexis.lebrun', 'fast', 20, 'FR', 2900, CURRENT_TIMESTAMP, 1, 1, 1),
(10, 'felix.lebrun', 'penhold', 17, 'FR', 2950, CURRENT_TIMESTAMP, 1, 5, 5);

-- 7. Insertion de la relation Player <-> PlayerTag (mapping)
INSERT INTO player_tags (player_id, tag_id) VALUES
(1, 1), (1, 4),
(2, 1), (2, 4),
(3, 1), (3, 4),
(4, 3), (4, 5),
(5, 1),
(6, 1), (6, 5),
(7, 1),
(8, 1),
(9, 1),
(10, 1);

-- Ajustement des séquences (Important pour PostgreSQL si on insère des ID manuellement)
SELECT setval('brand_id_seq', (SELECT MAX(id) FROM brand));
SELECT setval('blade_id_seq', (SELECT MAX(id) FROM blade));
SELECT setval('rubber_id_seq', (SELECT MAX(id) FROM rubber));
SELECT setval('player_tag_id_seq', (SELECT MAX(id) FROM player_tag));
SELECT setval('player_id_seq', (SELECT MAX(id) FROM player));
