spring.application.name=kijoukoi-backend

# Database configuration
spring.datasource.url=jdbc:postgresql://altaria.proxy.rlwy.net:12064/railway
spring.datasource.username=postgres
spring.datasource.password=FObehDHkgARchriUzeqDjHfjrDpUhZnm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
